services:
  mathia-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: mathia-frontend
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - mathia_network
      - fintools
    restart: unless-stopped
    env_file:
      - src/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mathia-frontend.rule=Host(`mathia.localhost`)"
      - "traefik.http.routers.mathia-frontend.entrypoints=web"
      - "traefik.http.services.mathia-frontend.loadbalancer.server.port=5173"
      - "traefik.docker.network=fintools"

networks:
  mathia_network:
    external: true
    name: mathia_network
  fintools:
    external: true
    name: fintools
