version: "3.8"

services:
  mathia-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mathia-frontend
    ports:
      - "3000:80"
    networks:
      - mathia_network
    restart: unless-stopped

networks:
  mathia_network:
    external: true
    name: mathia_network
